### ISSUE TITLE
Feature Request: Build for armv6 

### ISSUE THREAD

**Issue by schumi4** [gabe565/CastSponsorSkip#10]
Hi,

I've been using [nichobi/sponsorblockcast](https://github.com/nichobi/sponsorblockcast/) on an old RPi B without problems.
After installing through apt I receive `Illegal Operation` on starting CastSponsorSkip.

Is providing a build vor armv6 possible?
Thanks in advance!

**Comment by gabe565** [comment]
That should be possible! Let me add an armv6 target and see if the build passes.

**Comment by gabe565** [comment]
Frustratingly, it seems like Debian groups together `armv6` and `armv7` devices and calls them both `armhf`. I could disable the `armv7` build, but it runs faster on devices that support it so I'd rather keep it if possible. I may need to push `armv6` builds to a separate package. I might call it `castsponsorskip-armv6`?

**Comment by gabe565** [comment]
Alright I went ahead and replaced `armv7` with `armv6` for now. Can you test?

**Comment by gabe565** [comment]
Amazing!

Sure, if you don't mind creating an issue then I might need your help with testing. I have YouTube Premium and haven't been able to test the ad skip, even though I was _pretty_ sure it would work.
