### ISSUE TITLE
Video Detection not occurring until 30s-45s into videos usually

### ISSUE THREAD

**Issue by QueenLinuxGlitch** [gabe565/CastSponsorSkip#11]
Using new version, on advise to not change pause interval
Both the device running the program (Windows 11 Laptop) and the YouTube-playing chromecast Ultra w/ Google TV (Using standard youtube app) are on ethernet.
Still most of the time, the detection of the playback of a video doesn't occur until 30s-45s in, sometimes missing content at the beginning of the video

**Comment by gabe565** [comment]
Oh I see what you mean now. Hmm video play detection works almost instantly for me. I have two thoughts:

1. It's possible that not all devices send an event when the video starts, but that seems to be part of the Cast spec. What device are you casting to?
2. It's also possible that something doesn't get correctly set up on Windows, so the events don't work. I'll do some testing in Windows ASAP!

**Comment by gabe565** [comment]
For reference, here's how quickly streams get found in my case. I've only tested with macOS and Linux so far so that may be the difference here.


https://github.com/gabe565/CastSponsorSkip/assets/7717888/1ad520d1-361d-447a-9b1a-3fbab3cd64bf

**Comment by QueenLinuxGlitch** [comment]
So in my case, here's my full breakdown. a Chromecast Ultra w/ Google TV running Android 12, and I am not actually casting, I am playing the videos through the app loaded onto my chromecast, so that may be a difference there. As mentioned before, the two relevant devices are ethernet-ed in. Hoping that helps give context

**Comment by gabe565** [comment]
Thanks! Hmm so I only ever cast. I'll see if it behaves similarly for me if I start a video directly on the device!

**Comment by gabe565** [comment]
#12 made me realize videos weren't being considered as playing when they were buffering. Ads also set the status to buffering, so that may have been the problem here. Can you update to [v0.3.0](https://github.com/gabe565/CastSponsorSkip/releases/tag/v0.3.0) and test again? Thank you!

**Comment by QueenLinuxGlitch** [comment]
Probably unrelated, but what does it mean when "Failed to find video on Youtube", "Search returned no videos", was just on a video with sponsor and that was in the log immediately

**Comment by QueenLinuxGlitch** [comment]
Otherwise, detection is working immediately, so problem solved lol, but question above

**Comment by gabe565** [comment]
Interesting! Lol It's good to know the delays are fixed at least.

I'll do some more testing. I suspect that might have happened because it started looking for the video ID before the actual video was playing. Maybe due to buffering or an ad, but it tried to find the video ID with the YouTube API a couple of times before it was able to find the video data. I'll see what I can figure out, but hey at least it's working!

**Comment by QueenLinuxGlitch** [comment]
Indeed!

**Comment by QueenLinuxGlitch** [comment]
As of yesterday, no detections are occurring. Restarted the CLI multiple times, connects to both my cast devices immediately, but no youtube streams are being read anymore
