### ISSUE TITLE
Initial setup gets stuck when discovering android TV

### ISSUE THREAD

**Issue by topes1** [gabe565/CastSponsorSkip#120]
Using the docker command to install it gets stuck at connected to TV, its running android TV 11. IsponsorBlock stopped working as well. Can provide details if you tell me how.

**Comment by topes1** [comment]
![image](https://github.com/user-attachments/assets/7bc67f9e-8224-4f10-9d51-c301b7a2f5dd)

**Comment by gabe565** [comment]
It looks like it successfully connected to all of your devices, so I don't think it's stuck. Does it never skip videos? Could you run again with `--env=LOG_LEVEL=debug`?

**Comment by topes1** [comment]
The problem is solved, the issue was the missing api key.
