### ISSUE TITLE
ERROR Failed to query segments

### ISSUE THREAD

**Issue by bruvv** [gabe565/CastSponsorSkip#13]
When I am running this in docker I am getting the following error, not sure what is wrong, any idea @gabe565 ?
```
2023/08/27 10:51:24 INFO Searching for devices...
2023/08/27 10:51:24 INFO Connected to cast device. device="Bedroom TV"
2023/08/27 10:51:25 INFO Detected video stream. device="Bedroom TV" video_id=5o1EwksAOWI
2023/08/27 10:51:25 ERROR Failed to query segments. Retrying... device="Bedroom TV" error="invalid response status: 400 Bad Request"
```

**Comment by gabe565** [comment]
That happened in #5 due to categories being parsed incorrectly. Tomorrow I can add the response body to the log message so it's more obvious what's going on here.

In the mean time, are you setting any categories?

**Comment by bruvv** [comment]
Ah indeed, while using `,` it does work :) I will close this one and update my documentation. (https://github.com/alexbelgium/hassio-addons/tree/master/sponsorblockcast)

**Comment by gabe565** [comment]
That explains it. The first couple of CastSponsorSkip releases had an interop that converted ` ` to `,` but I didn't think anybody would use it so I removed it during a refactor 😬 Sounds like maybe I should add it back

**Comment by bruvv** [comment]
Could be better since the [sponsorblockcast](https://github.com/nichobi/sponsorblockcast) used spaces

**Comment by gabe565** [comment]
Oh good catch. I'll go ahead and add it back! I tried to support as many of the sponsorblockcast envs so that seems important to keep

**Comment by gabe565** [comment]
Ok, in v0.3.1 I added support for the `SBCSCANINTERVAL` and `SBCPOLLINTERVAL` envs, along with adding a test for all of these. Should make upgrading easier for users :)
