### ISSUE TITLE
Bug: 0.3.1 outputs help text and quits

### ISSUE THREAD

**Issue by schumi4** [gabe565/CastSponsorSkip#14]
Since teh update to 0.3.1 I can only get CSS to output the help text and quit.

Has the default behaviour so start it with `castsponsorskip` been changed? The service fails as well.

**Comment by schumi4** [comment]
Addendum:

it outputs an error:

```
root@DietPi:~# castsponsorskip
Error: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information
Usage:
  castsponsorskip [flags]
[...cont. help]
```

**Comment by gabe565** [comment]
Oh good catch. That's a bug 🤦 Fixing that immediately!

**Comment by schumi4** [comment]
Seems to work!
