### ISSUE TITLE
Using the mute feature but not SponsorBlock is difficult and sucks.

### ISSUE THREAD

**Issue by squeakyneb** [gabe565/CastSponsorSkip#42]
I want to use the ad muting and skipping features of this tool, but I don't want to use SponsorBlock. Many of the channels I watch actually do very funny sponsor segments and I enjoy them.

The obvious option seemed to be setting env var `CSS_CATEGORIES`.  `CSS_CATEGORIES=''` gives me default behaviour (the thing I don't want). So does `CSS_CATEGORIES=' '`. I had to really fool the config system with `CSS_CATEGORIES=' , '` to get it to just have an empty list of zero categories.

This is a pretty rough user experience. Variables explicitly set as being empty should be interpreted as empty, not as unset. It's not the same.

**Comment by gabe565** [comment]
@squeakyneb I agree that empty envs aren't the same as unset values, and that it should be possible to disable the SponsorBlock while keeping ad skip, but I also want to mention that loading these values from envs is handled by a package and not by me, so it must be desired behavior for a lot of projects.

Let me decide the best way to implement this. Should be a pretty quick thing to add. In the mean time, the fact that `CSS_CATEGORIES=' , '` works is hilarious.

**Comment by gabe565** [comment]
@squeakyneb I'm releasing v0.6.0 which lets you set `CSS_SKIP_SPONSORS=false` to disable sponsor skip.
