### ISSUE TITLE
Failing to Query Segments on Videos

### ISSUE THREAD

**Issue by eroc1990** [gabe565/CastSponsorSkip#5]
Running environment is Ubuntu 22.04.3 LTS x86_64 VM under Proxmox, installing through the apt repo and configured using systemctl overrides.

Everything but segment retrieval seems to be working. When I tail the systemctl logs, I see it reaching out to and establishing connections with all cast devices on my network. Video lookup succeeds via the YouTube API key provided, but segment retrieval returns the error "Invalid response status: 400 bad request".

The application and my Cast devices are located on separate VLANs, but I have firewall rules created to allow traffic between CastSponsorSkip and the Cast devices to flow bidirectionally, so it isn't a reachability issue. Is there a way to turn up the verboseness of the logs to see if anything else is being caught? I can provide my journalctl tail if needed.

**Comment by gabe565** [comment]
Thanks for opening this! None of my devices seem to require a YouTube API keys, so while I've done some testing, it's admittedly less thorough than the rest. Let me do some troubleshooting on my end. I do have a change ready which will add a `CSS_LOG_LEVEL` env so I could also push that and see if anything more useful turns up.

**Comment by gabe565** [comment]
@eroc1990 Could you send a video you've tested with? I want to test the API lookup using the same video ID if possible.

**Comment by gabe565** [comment]
@eroc1990 Nevermind, I found the issue. It looks like custom categories aren't being split correctly! Fixing that now.

**Comment by eroc1990** [comment]
That was quick! Thanks! Let me know when you have this updated in the apt repo and I'll pull, test again, and tail journalctl.

**Comment by gabe565** [comment]
@eroc1990 You're welcome! It looks like the config library I'm using handles envs a little bit differently than it handles flags, so the category _flag_ could be comma-separated, but the env would had to be space-separated. (see spf13/viper#380)

I just released v0.1.3 which supports both comma or space separated values! Can you update your local instance and let me know if the issue is resolved?

**Comment by eroc1990** [comment]
Tested and confirmed that it is working on the one Chromecast I had a chance to test very quickly. Segments are being detected and (from what I can tell) skipped.

**Comment by eroc1990** [comment]
Marking closed because I had a chance to test more on a second Chromecast near me and was able to replicate the success from the first one I tested, each time detecting the segments per what I specified in my override.conf.
