### ISSUE TITLE
Disable sponsor skipping and only skip ads? 

### ISSUE THREAD

**Issue by Zae** [gabe565/CastSponsorSkip#77]
Is it possible to configure the app to only skip ads and not sponsored segments?

Right now I added a non existing category to get this behaviour, but this does throw a lot of errors in the logs and tries to contact the api, while this would be unnecessary when only skipping ads.

As a side node, could the categories be better documenten? I could not find anywhere what the possible categories actually mean.

**Comment by gabe565** [comment]
Sure! I'll add an environment variable for that in the next update.

I also just came across the [SponsorBlock category breakdown](https://wiki.sponsor.ajay.app/w/Guidelines#Category_Breakdown), which seems a lot more helpful. If you agree, I'd happily add a link to that in the readme.

**Comment by Zae** [comment]
That would be amazing!

**Comment by gabe565** [comment]
Ha wait a second, I've already added a flag for this! I just didn't add it to the main readme, since I assumed it would be less commonly used. Try `--skip-sponsors=false` or `CSS_SKIP_SPONSORS=false`!
